name: 'tests'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Runner
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          sudo apt-get install alsa-base
          sudo apt-get install libasound2-dev
          sudo apt-get install alsa-utils
          sudo apt-get install libpulse-dev
          sudo apt-get install pulseaudio-utils
          sudo modprobe snd
         sudo systemctl status systemd-modules-load.service
         
      - name: Get audio info
        run: |
          ls /proc/asound
          aplay -L
          pactl list cards

      - name: build
        run: |
          mkdir build && cd build
          cmake ..
          make
      
      - name: test
        run: cd build && make test

      - name: save results
        uses: actions/upload-artifact@v3

        with:
          name: test_results
          path: build/test_results.json